--pedi pro chat fazer um arquivo para facilitar a criaçao do banco pra voce.
--mudei basicamente todo meu codigo pra funcionar no meu banco ent espero que ajude 

-- ============================================================
-- SISTEMA DE AGENDAMENTO DE FAXINA
-- Banco: PostgreSQL
-- Arquivo: backend/sql/schema.sql
--
-- ATENCAO:
-- Este script RECRIA as tabelas do sistema e apaga os dados
-- existentes nessas tabelas. Execute somente em banco de teste.
--
-- Execucao sugerida:
--   psql -U SEU_USUARIO -d SEU_BANCO -f backend/sql/schema.sql
-- ============================================================

BEGIN;

-- ============================================================
-- 1. REMOVER TABELAS EXISTENTES (ordem respeita as chaves FK)
-- ============================================================

DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS comentario_agendamento CASCADE;
DROP TABLE IF EXISTS historico_agendamento CASCADE;
DROP TABLE IF EXISTS agendamento CASCADE;
DROP TABLE IF EXISTS profissional_disponibilidade CASCADE;
DROP TABLE IF EXISTS materials CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS profissional CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;

-- ============================================================
-- 2. USUARIOS E AUTENTICACAO
-- ============================================================

CREATE TABLE users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(10) NOT NULL DEFAULT 'user',
    CONSTRAINT ck_users_role CHECK (role IN ('admin', 'user'))
);

-- ============================================================
-- 3. CLIENTES E PROFISSIONAIS
-- ============================================================

CREATE TABLE cliente (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome     VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email    VARCHAR(254) UNIQUE,
    endereco VARCHAR(200) NOT NULL
);

CREATE TABLE profissional (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome     VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    ativo    BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- 4. DISPONIBILIDADE DOS PROFISSIONAIS
-- dia_semana: 1 = segunda-feira ... 7 = domingo
-- ============================================================

CREATE TABLE profissional_disponibilidade (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profissional_id INTEGER NOT NULL,
    dia_semana      SMALLINT NOT NULL,
    hora_inicio     TIME NOT NULL,
    hora_fim        TIME NOT NULL,

    CONSTRAINT fk_disp_profissional
        FOREIGN KEY (profissional_id)
        REFERENCES profissional (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_disp_prof_dia
        UNIQUE (profissional_id, dia_semana),

    CONSTRAINT ck_disp_dia
        CHECK (dia_semana BETWEEN 1 AND 7),

    CONSTRAINT ck_disp_hora
        CHECK (hora_fim > hora_inicio)
);

-- ============================================================
-- 5. AGENDAMENTOS
-- ============================================================

CREATE TABLE agendamento (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id       INTEGER NOT NULL,
    profissional_id  INTEGER NOT NULL,
    tipo_servico     VARCHAR(12) NOT NULL,
    data_agendamento DATE NOT NULL,
    hora_inicio      TIME NOT NULL,
    hora_fim         TIME NOT NULL,
    status           VARCHAR(10) NOT NULL DEFAULT 'agendado',
    observacoes      VARCHAR(255),
    criado_em        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_agend_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES cliente (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_agend_profissional
        FOREIGN KEY (profissional_id)
        REFERENCES profissional (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_agend_tipo
        CHECK (tipo_servico IN ('residencial', 'comercial')),

    CONSTRAINT ck_agend_status
        CHECK (status IN ('agendado', 'concluido', 'cancelado')),

    CONSTRAINT ck_agend_hora
        CHECK (hora_fim > hora_inicio)
);

CREATE INDEX idx_agend_conflito
    ON agendamento (profissional_id, data_agendamento, hora_inicio, hora_fim);

-- ============================================================
-- 6. HISTORICO DE ALTERACOES DOS AGENDAMENTOS
-- ============================================================

CREATE TABLE historico_agendamento (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agendamento_id  INTEGER,
    cliente_id      INTEGER NOT NULL,
    profissional_id INTEGER NOT NULL,
    usuario_id      INTEGER NOT NULL,
    acao            VARCHAR(10) NOT NULL,
    detalhes        VARCHAR(255),
    data_operacao   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_hist_agendamento
        FOREIGN KEY (agendamento_id)
        REFERENCES agendamento (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_hist_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES cliente (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_hist_profissional
        FOREIGN KEY (profissional_id)
        REFERENCES profissional (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_hist_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_hist_acao
        CHECK (acao IN ('criado', 'editado', 'cancelado', 'excluido'))
);

CREATE INDEX idx_hist_agendamento
    ON historico_agendamento (agendamento_id);

-- ============================================================
-- 7. COMENTARIOS DOS AGENDAMENTOS
-- ============================================================

CREATE TABLE comentario_agendamento (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agendamento_id INTEGER NOT NULL,
    comentario     VARCHAR(500) NOT NULL,
    criado_em      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_comentario_agendamento
        FOREIGN KEY (agendamento_id)
        REFERENCES agendamento (id)
        ON DELETE CASCADE,

    CONSTRAINT ck_comentario_tamanho
        CHECK (CHAR_LENGTH(comentario) BETWEEN 1 AND 500)
);

-- ============================================================
-- 8. MATERIAIS (funcionalidade de demonstracao/testes)
-- ============================================================

CREATE TABLE materials (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(150) NOT NULL,
    category VARCHAR(100) NOT NULL
);

CREATE TABLE comments (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id INTEGER NOT NULL,
    comment     TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_comments_material
        FOREIGN KEY (material_id)
        REFERENCES materials (id)
        ON DELETE CASCADE,

    CONSTRAINT ck_comments_length
        CHECK (CHAR_LENGTH(comment) BETWEEN 1 AND 500)
);

CREATE INDEX idx_comments_material
    ON comments (material_id, created_at DESC);

-- ============================================================
-- 9. DADOS DE TESTE: USUARIOS
-- Os valores de password_hash sao hashes bcrypt existentes.
-- ============================================================

INSERT INTO users (id, name, email, password_hash, role) VALUES
    (1, 'Administrador', 'admin@faxina.com',
     '$2b$10$bCL9CSIS4g9.URMZ9Bwnk.MntVantxyw/jJcq5Hi3mw.0dJpTMrZK', 'admin'),
    (2, 'Carla Mendes', 'atendente1@faxina.com',
     '$2b$10$aEydezyYSq2ZdfXtnpDjqehT6PrYrmsBReJjhruha7r5ioP8jsKBu', 'user'),
    (3, 'Rafael Costa', 'atendente2@faxina.com',
     '$2b$10$hoK75awjTaNfLhHXZpLXUOPjxlT.XAcQsmJQodHBl4rTWl7dFvgvK', 'user');

-- ============================================================
-- 10. DADOS DE TESTE: CLIENTES
-- ============================================================

INSERT INTO cliente (id, nome, telefone, email, endereco) VALUES
    (1, 'Ana Paula Martins', '(48) 99811-2233',
     'ana.martins@email.com', 'Rua das Acácias, 120, apto 302'),
    (2, 'Alfa Contabilidade', '(48) 3222-4410',
     'contato@alfacont.com', 'Av. Central, 850, sala 12'),
    (3, 'Carlos Eduardo Pereira', '(48) 99745-6120',
     'carlos.pereira@email.com', 'Rua do Sol, 45'),
    (4, 'Clínica Bem Viver', '(48) 3333-9087',
     'recepcao@bemviver.com', 'Rua das Flores, 300');

-- ============================================================
-- 11. DADOS DE TESTE: PROFISSIONAIS
-- ============================================================

INSERT INTO profissional (id, nome, telefone, ativo) VALUES
    (1, 'Maria Aparecida Souza', '(48) 99633-1010', TRUE),
    (2, 'João Pedro Lima', '(48) 99644-2020', TRUE),
    (3, 'Fernanda Ribeiro', '(48) 99655-3030', TRUE);

-- ============================================================
-- 12. DADOS DE TESTE: DISPONIBILIDADES
-- ============================================================

INSERT INTO profissional_disponibilidade
    (profissional_id, dia_semana, hora_inicio, hora_fim)
VALUES
    (1, 1, '08:00', '18:00'),
    (1, 2, '08:00', '18:00'),
    (1, 3, '08:00', '18:00'),
    (1, 4, '08:00', '18:00'),
    (1, 5, '08:00', '18:00'),
    (2, 1, '08:00', '18:00'),
    (2, 2, '08:00', '18:00'),
    (2, 3, '08:00', '18:00'),
    (2, 4, '08:00', '18:00'),
    (2, 5, '08:00', '18:00'),
    (3, 1, '08:00', '14:00'),
    (3, 2, '08:00', '14:00'),
    (3, 3, '08:00', '14:00'),
    (3, 4, '08:00', '14:00'),
    (3, 5, '08:00', '14:00'),
    (3, 6, '08:00', '14:00');

-- ============================================================
-- 13. DADOS DE TESTE: AGENDAMENTOS
-- ============================================================

INSERT INTO agendamento
    (id, cliente_id, profissional_id, tipo_servico, data_agendamento,
     hora_inicio, hora_fim, status, observacoes)
VALUES
    (1, 1, 1, 'residencial', '2026-10-08', '08:00', '12:00',
     'agendado', 'Faxina completa, trazer produtos próprios'),
    (2, 2, 2, 'comercial', '2026-10-08', '13:00', '18:00',
     'agendado', 'Escritório com 6 salas, incluir vidros'),
    (3, 3, 3, 'residencial', '2026-10-10', '09:00', '13:00',
     'agendado', 'Limpeza pesada de cozinha e banheiros'),
    (4, 4, 1, 'comercial', '2026-10-13', '14:00', '17:00',
     'agendado', 'Clínica: limpeza com produtos hospitalares'),
    (5, 3, 2, 'residencial', '2026-10-09', '09:00', '12:00',
     'cancelado', 'Cancelado a pedido do cliente'),
    (6, 1, 1, 'residencial', '2026-09-30', '08:00', '12:00',
     'concluido', 'Serviço realizado sem ocorrências');

-- ============================================================
-- 14. DADOS DE TESTE: HISTORICO
-- ============================================================

INSERT INTO historico_agendamento
    (agendamento_id, cliente_id, profissional_id, usuario_id, acao,
     detalhes, data_operacao)
VALUES
    (1, 1, 1, 2, 'criado',
     'Agendamento criado pelo atendente', '2026-10-05 09:15:00-03'),
    (2, 2, 2, 2, 'criado',
     'Agendamento criado pelo atendente', '2026-10-05 10:40:00-03'),
    (3, 3, 3, 3, 'criado',
     'Agendamento criado pelo atendente', '2026-10-06 14:05:00-03'),
    (3, 3, 3, 1, 'editado',
     'Horário de início alterado de 08:00 para 09:00', '2026-10-06 17:20:00-03'),
    (4, 4, 1, 3, 'criado',
     'Agendamento criado pelo atendente', '2026-10-06 15:30:00-03'),
    (5, 3, 2, 2, 'criado',
     'Agendamento criado pelo atendente', '2026-10-06 16:00:00-03'),
    (5, 3, 2, 2, 'cancelado',
     'Cancelado a pedido do cliente', '2026-10-07 08:50:00-03'),
    (6, 1, 1, 1, 'criado',
     'Agendamento criado pelo administrador', '2026-09-28 11:00:00-03');

-- ============================================================
-- 15. DADOS DE TESTE: MATERIAIS
-- ============================================================

INSERT INTO materials (id, name, category) VALUES
    (1, 'Produtos de limpeza', 'Limpeza'),
    (2, 'Aspirador de pó', 'Equipamentos'),
    (3, 'Luvas de proteção', 'EPIs');

-- ============================================================
-- 16. COMENTARIOS DE TESTE DOS AGENDAMENTOS E MATERIAIS
-- ============================================================

INSERT INTO comentario_agendamento
    (agendamento_id, comentario)
VALUES
    (1, 'Cliente pediu atenção especial à cozinha.'),
    (2, 'Confirmar acesso ao escritório com o responsável.');

INSERT INTO comments (material_id, comment) VALUES
    (1, 'Produto muito útil para a limpeza diária.'),
    (2, 'Verificar o filtro antes de utilizar.'),
    (3, 'Conferir o tamanho das luvas antes do serviço.');

-- ============================================================
-- 17. SINCRONIZAR SEQUENCIAS DOS IDS
-- Evita conflito após inserções com IDs definidos manualmente.
-- ============================================================

SELECT setval(pg_get_serial_sequence('users', 'id'),
              COALESCE((SELECT MAX(id) FROM users), 1),
              EXISTS (SELECT 1 FROM users));

SELECT setval(pg_get_serial_sequence('cliente', 'id'),
              COALESCE((SELECT MAX(id) FROM cliente), 1),
              EXISTS (SELECT 1 FROM cliente));

SELECT setval(pg_get_serial_sequence('profissional', 'id'),
              COALESCE((SELECT MAX(id) FROM profissional), 1),
              EXISTS (SELECT 1 FROM profissional));

SELECT setval(pg_get_serial_sequence('profissional_disponibilidade', 'id'),
              COALESCE((SELECT MAX(id) FROM profissional_disponibilidade), 1),
              EXISTS (SELECT 1 FROM profissional_disponibilidade));

SELECT setval(pg_get_serial_sequence('agendamento', 'id'),
              COALESCE((SELECT MAX(id) FROM agendamento), 1),
              EXISTS (SELECT 1 FROM agendamento));

SELECT setval(pg_get_serial_sequence('historico_agendamento', 'id'),
              COALESCE((SELECT MAX(id) FROM historico_agendamento), 1),
              EXISTS (SELECT 1 FROM historico_agendamento));

SELECT setval(pg_get_serial_sequence('comentario_agendamento', 'id'),
              COALESCE((SELECT MAX(id) FROM comentario_agendamento), 1),
              EXISTS (SELECT 1 FROM comentario_agendamento));

SELECT setval(pg_get_serial_sequence('materials', 'id'),
              COALESCE((SELECT MAX(id) FROM materials), 1),
              EXISTS (SELECT 1 FROM materials));

SELECT setval(pg_get_serial_sequence('comments', 'id'),
              COALESCE((SELECT MAX(id) FROM comments), 1),
              EXISTS (SELECT 1 FROM comments));

COMMIT;

-- ============================================================
-- 18. CONSULTAS OPCIONAIS PARA CONFERIR OS DADOS
-- Execute separadamente quando quiser verificar:
--
-- SELECT * FROM users ORDER BY id;
-- SELECT * FROM cliente ORDER BY id;
-- SELECT * FROM profissional ORDER BY id;
-- SELECT * FROM agendamento ORDER BY id;
-- SELECT * FROM historico_agendamento ORDER BY id;
-- SELECT * FROM comentario_agendamento ORDER BY id;
-- SELECT * FROM materials ORDER BY id;
-- SELECT * FROM comments ORDER BY id;
-- ============================================================